Repository Arquisoft/wiq_en1b, pull requests merged in 2024-04, with the labels that each got.

#67 Question generation general
  package-lock.json
  questionGenerator/src/main/java/questionGenerator/generator/AbstractGenerator.java
  questionGenerator/src/main/java/questionGenerator/generator/RightAnswerIsEntity.java
  questionGenerator/src/main/java/questionGenerator/generator/specificGenerators/CapitalGenerator.java
  questionGenerator/src/main/java/questionGenerator/generator/specificGenerators/LanguageGenerator.java
  questionGenerator/src/main/java/questionGenerator/generator/specificGenerators/PopulationGenerator.java
  questionGenerator/src/main/java/questionGenerator/generator/specificGenerators/SizeGenerator.java
  questionGenerator/src/main/java/questionGenerator/question/Question.java
  questionGenerator/src/test/java/questionGenerator/QuestionGeneratorTests.java
  questionGenerator/src/test/java/questionGenerator/question/QuestionTests.java
Labels: enhancement

#80 Updating doc
  docs/images/08-Domain-Model.png
  docs/images/Deployed-Infrastructure.png
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
Labels: documentation

#101 90 user policies
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/loginAndRegistration/AddUser.js
  webapp/src/components/loginAndRegistration/AddUser.test.js
  webapp/src/custom.css
  webapp/src/translations/en/global.json
  webapp/src/translations/es/global.json
  webapp/src/translations/tk/global.json
Labels: enhancement, frontend, design

#133 Fixed small problems with the generation
  questionGenerator/src/main/java/questionGenerator/generator/answersAreEntites/withSubProperties/AnswersAreEntitiesWithSubProperties.java
  questionGenerator/src/main/java/questionGenerator/generator/answersAreNotEntites/PopulationGenerator.java
  questionGenerator/src/main/java/questionGenerator/generator/answersAreNotEntites/SizeGenerator.java
  questionGenerator/src/main/java/questionGenerator/question/answers/formatAnswers/SetAmountOfDecimals.java
Labels: bug

#144 Improved the readme
  README.md
Labels: documentation, enhancement

#145 Documentation fixes
  docs/src/04_solution_strategy.adoc
  docs/src/10_quality_requirements.adoc
Labels: documentation

#148 Footer and about
  webapp/public/person1.jpg
  webapp/public/person2.jpg
  webapp/public/person3.jpg
  webapp/public/person4.jpg
  webapp/public/person5.jpg
  webapp/public/person6.jpg
  webapp/src/App.js
  webapp/src/components/fragments/About.js
  webapp/src/components/fragments/About.test.js
  webapp/src/components/fragments/BackButtonToGameMenu.test.js
  webapp/src/components/fragments/Footer.js
  webapp/src/components/fragments/Footer.test.js
  webapp/src/custom.css
  webapp/src/translations/en/global.json
  webapp/src/translations/es/global.json
  webapp/src/translations/tk/global.json
Labels: enhancement

#167 Documentation fixes
  docs/index.adoc
  docs/src/12_testing.adoc
  docs/src/13_glossary.adoc
Labels: documentation

#168 Load tests
  webapp/load_tests/BURSTGuestTest.scala
  webapp/load_tests/BURSTLoginTest.scala
  webapp/load_tests/GuestTest.scala
  webapp/load_tests/GuestTest2.scala
  webapp/load_tests/LoginTest.scala
Labels: test
